#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Install packages.
#======================================================================================================================

bf-echo "Installing packages..."
apk add --no-cache \
    bash \
    curl \
    jq \
    openssl
bf-done


#======================================================================================================================
# Download getssl script.
#======================================================================================================================

VERSION=`cat /tmp/GETSSL_VERSION`
bf-echo "Downloading getssl ${VERSION}."

GETSSL=/usr/lib/bf/proxy/getssl
wget -O ${GETSSL} "https://raw.githubusercontent.com/srvrco/getssl/v${VERSION}/getssl"
chmod +x ${GETSSL}
bf-done


#======================================================================================================================
# Cleanup.
#======================================================================================================================

bf-echo "Cleaning up Nginx sites definitions."
rm -rf /etc/nginx/sites
bf-done


#======================================================================================================================
# Create and link Nginx directories.
#======================================================================================================================

bf-echo "Creating and linking Nginx directories."

mkdir /sites
ln -s /sites /etc/nginx/sites

mkdir -p /ssl/certs
