#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Build jq from source.
#======================================================================================================================

bf-echo "Installing build dependencies..."
apk add --no-cache --virtual .install \
    alpine-sdk \
    autoconf \
    automake \
    git \
    libtool \
    oniguruma-dev

bf-echo "Cloning jq source..."
cd /tmp && \
    git clone https://github.com/stedolan/jq.git && \
    cd jq

bf-echo "Configuring jq..."
autoreconf -fi
./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --disable-docs

bf-echo "Installing jq..."
make
make install

bf-echo "Removing jq installation..."
apk del .install

bf-done


#======================================================================================================================
# Install packages.
#======================================================================================================================

bf-echo "Installing packages..."
apk add --no-cache \
    bash \
    curl \
    oniguruma \
    openssl
bf-done


#======================================================================================================================
# Download getssl script.
#======================================================================================================================

VERSION=`cat /tmp/GETSSL_VERSION`
bf-echo "Downloading getssl ${VERSION}."

GETSSL=/usr/lib/bf/proxy/getssl
wget -O ${GETSSL} "https://raw.githubusercontent.com/srvrco/getssl/v${VERSION}/getssl"
chmod +x ${GETSSL}
bf-done


#======================================================================================================================
# Cleanup.
#======================================================================================================================

bf-echo "Cleaning up Nginx sites definitions."
rm -rf /etc/nginx/sites
bf-done


#======================================================================================================================
# Create and link Nginx directories.
#======================================================================================================================

bf-echo "Creating and linking Nginx directories."

mkdir /sites
ln -s /sites /etc/nginx/sites

mkdir -p /ssl/certs
