#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Check for clean install.
#======================================================================================================================

if [ "${PROXY_CLEAN_INSTALL}" = "1" ] ; then

    bf-echo "Clean install detected..."
    bf-rmrf "${PROXY_GETSSL_GLOBAL_CFG}"
    bf-rmrf "${PROXY_SSL_DHPARAM}"
    bf-rmrf "${PROXY_SSL_CERTS}/*"
    bf-rmrf "${PROXY_SITES}/*"
    bf-done

fi


#======================================================================================================================
# Run initialisation script.
#======================================================================================================================

ssl-init
