#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Check for clean install.
#======================================================================================================================

if [ "${PROXY_CLEAN_INSTALL}" = "1" ] ; then

    bf-echo "Clean install detected..."
    bf-rmrf "${PROXY_GETSSL_GLOBAL_CFG}"
    bf-rmrf "${PROXY_SSL_DHPARAM}"
    bf-rmrf "${PROXY_SSL_CERTS}/*"
    bf-rmrf "${PROXY_SITES}/*"
    bf-done

fi


#======================================================================================================================
# If there is no SSL configuration file, and auto environment variables are set, generate config.
#======================================================================================================================

if [ ! -f "${PROXY_SSL_CONF}" ] && [ -n "${PROXY_AUTO_PRIMARY-}" ] && [ -n "${PROXY_AUTO_UPSTREAM-}" ] ; then

    # generate conf
    bf-echo "Generating conf.json using auto environment variables."
    bf-esh ${BF_TEMPLATES}/conf.json.esh ${PROXY_SSL_CONF}
    bf-env "PROXY_AUTO" "1"

    # if there are aliases enable canonical redirection
    [[ -n "${PROXY_AUTO_ALIASES-}" ]] && bf-env "PROXY_SSL_REDIRECT_TO_CANONICAL" "1"

    # initialise all domains (proxy plus auto)
    ssl-init -a


#======================================================================================================================
# Run initialisation script only for the proxy domain.
#======================================================================================================================

else

    ssl-init -d "proxy"

fi
