#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate NASXI configuration.
#======================================================================================================================

bf-echo "Generating NASXI files."
bf-esh ${BF_TEMPLATES}/nasxi.conf.esh /etc/nginx/helpers/nasxi.conf
bf-done
