#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate NAXSI configuration.
#======================================================================================================================

if [ "${PROXY_ENABLE_NAXSI-}" = "1" ] ; then

    bf-echo "Generating NAXSI files."
    bf-esh ${BF_TEMPLATES}/naxsi.conf.esh /etc/nginx/helpers/naxsi.conf
    bf-done

else

    bf-echo "NAXSI not enabled."

fi
