#!/usr/bin/with-contenv bash

#======================================================================================================================
# Run checks
#======================================================================================================================

source ${INC}/check.sh


#======================================================================================================================
# Require source files
#======================================================================================================================

source ${INC}/replace.sh
source ${INC}/setup-global.sh
source ${INC}/setup-nginx.sh
source ${INC}/setup-ssl.sh


#======================================================================================================================
# Set up global SSL configuration
#======================================================================================================================

bcg-echo "Setting up getssl..."
setup_global
bcg-done


#======================================================================================================================
# Check for PROXY_URI
#======================================================================================================================

[[ -z "${PROXY_URI-}" ]] && bcg-error "PROXY_URI must be set."

bcg-echo "Setting up default server ${PROXY_URI}..."
declare -a BLANK_ALIAS=()

bcg-echo "  . Nginx..."
setup_nginx 1 ${PROXY_URI} "http://localhost" BLANK_ALIAS ""

bcg-echo "  . SSL..."
setup_ssl ${PROXY_URI} BLANK_ALIAS

bcg-ok "  . done."


#======================================================================================================================
# Set up Nginx and SSL for each primary domain
#======================================================================================================================

bcg-echo "Setting up domains..."
for DN in "${!DOMAINS[@]}" ; do

    UP=${DOMAINS[${DN}]}     # upstream server
    AL=(${ALIASES[${DN}]})   # domain aliases
    CF=${NGXCONF[${DN}]}     # domain Nginx configuration default / custom

    bcg-echo " .. ${DN}"

    bcg-echo "  . Nginx..."
    setup_nginx 0 ${DN} ${UP} AL ${CF}

    bcg-echo "  . SSL..."
    setup_ssl ${DN} AL

    bcg-ok "  . done."

done
bcg-ok "Domains set up."
