#!/usr/bin/with-contenv bash

#======================================================================================================================
# Run checks
#======================================================================================================================

source ${INC}/check.sh


#======================================================================================================================
# Require source files
#======================================================================================================================

source ${INC}/replace.sh
source ${INC}/setup-global.sh
source ${INC}/setup-nginx.sh
source ${INC}/setup-ssl.sh


#======================================================================================================================
# Set up global SSL configuration
#======================================================================================================================

_echo "Setting up getssl..."
setup_global
_done


#======================================================================================================================
# Check for PROXY_URI
#======================================================================================================================

[[ -z "${PROXY_URI}" ]] && _error "PROXY_URI must be set."

_echo "Setting up default server ${PROXY_URI}..."
declare -a BLANK_ALIAS=()

_echo "  . Nginx..."
setup_nginx true ${PROXY_URI} "http://localhost" BLANK_ALIAS ""

_echo "  . SSL..."
setup_ssl ${PROXY_URI} BLANK_ALIAS

_ok "  . done."


#======================================================================================================================
# Set up Nginx and SSL for each primary domain
#======================================================================================================================

_echo "Setting up domains..."
for DN in "${!DOMAINS[@]}" ; do

    UP=${DOMAINS[${DN}]}     # upstream server
    AL=(${ALIASES[${DN}]})   # domain aliases
    CF=${NGXCONF[${DN}]}     # domain Nginx configuration default / custom

    _echo " .. ${DN}"

    _echo "  . Nginx..."
    setup_nginx false ${DN} ${UP} AL ${CF}

    _echo "  . SSL..."
    setup_ssl ${DN} AL

    _ok "  . done."

    FIRST=false

done
_ok "Domains set up."
