#!/usr/bin/with-contenv bash

export BCG_E=`basename ${0}`


#======================================================================================================================
# Run checks
#======================================================================================================================

source ${INC}/check.sh


#======================================================================================================================
# Require source files
#======================================================================================================================

source ${INC}/replace.sh
source ${INC}/setup-global.sh
source ${INC}/setup-nginx.sh
source ${INC}/setup-ssl.sh


#======================================================================================================================
# Set up global SSL configuration
#======================================================================================================================

bcg-echo "Setting up getssl..."
setup_global
bcg-done


#======================================================================================================================
# Set up Nginx and SSL for proxy server
#======================================================================================================================

bcg-echo "Setting up default server ${PROXY_URI}..."

bcg-echo "  . Nginx..."
setup_nginx 1 ${PROXY_URI} "http://localhost" ""

bcg-echo "  . SSL..."
setup_ssl ${PROXY_URI} ""

bcg-ok "  . done."


#======================================================================================================================
# Set up Nginx and SSL for each domain
#======================================================================================================================

bcg-echo "Setting up domains..."
for DN in "${!DOMAINS[@]}" ; do

    UP=${DOMAINS[${DN}]}  # upstream server
    AL=${ALIASES[${DN}]}  # aliases
    CF=${NGXCONF[${DN}]}  # use default / custom Nginx config

    bcg-echo " .. ${DN}"

    bcg-echo "  . Nginx..."
    setup_nginx 0 ${DN} "${UP}" "${AL}" "${CF}"

    bcg-echo "  . SSL..."
    setup_ssl ${DN} "${AL}"

    bcg-ok "  . done."

done
bcg-ok "Domains set up."
