#!/usr/bin/with-contenv bash

#======================================================================================================================
# Run checks
#======================================================================================================================

source ${INC}/check.sh


#======================================================================================================================
# Request certificates for all domains
#   -U stop upgrade checks
#   -w set working directory
#======================================================================================================================

request() { /etc/ssl/getssl -U -w ${SSL_CERTS} ${1} ; }

bcg-echo "Requesting SSL certificates..."
request "${PROXY_URI}"
for DN in "${!DOMAINS[@]}" ; do
    bcg-echo " .. ${DN}"
    request ${DN}
done
bcg-done
