#!/usr/bin/with-contenv bash

#======================================================================================================================
# Define variables
#======================================================================================================================

export ACME_CHALLENGE=.well-known/acme-challenge
export GETSSL_CFG=getssl.cfg


#======================================================================================================================
# Define paths to directories and files
#======================================================================================================================

export INC=/etc/ssl/inc

export TEMPLATES=/etc/templates

export SSL=/ssl
export SSL_CERTS=${SSL}/certs
export SSL_DHPARAM=${SSL_CERTS}/dhparam.pem
export SSL_GLOBAL_CFG=${SSL_CERTS}/${GETSSL_CFG}

export SITES=/sites

export WWW=/www
export WWW_ACME_CHALLENGE=${WWW}/${ACME_CHALLENGE}
