#!/usr/bin/with-contenv bash

set -euo pipefail


#======================================================================================================================
# Add environment variable to S6 environment directory
#======================================================================================================================

add_env () { _echo "${1}=${2}" && printf "%s" $2 > /var/run/s6/container_environment/$1; }


#======================================================================================================================
# Define variables
#======================================================================================================================

ACME_CHALLENGE=.well-known/acme-challenge
add_env "ACME_CHALLENGE" "${ACME_CHALLENGE}"

GETSSL_CFG=getssl.cfg
add_env "GETSSL_CFG" "${GETSSL_CFG}"


#======================================================================================================================
# Define paths to directories and files
#======================================================================================================================

add_env "INC" "/etc/ssl/inc"

add_env "TEMPLATES" "/etc/templates"

SSL=/ssl
add_env "SSL" ${SSL}

SSL_CERTS=${SSL}/certs
add_env "SSL_CERTS" "${SSL_CERTS}"
add_env "SSL_DHPARAM" "${SSL_CERTS}/dhparam.pem"
add_env "SSL_GLOBAL_CFG" "${SSL_CERTS}/${GETSSL_CFG}"

add_env "SITES" "/sites"

WWW=/www
add_env "WWW" "${WWW}"
add_env "WWW_ACME_CHALLENGE" "${WWW}/${ACME_CHALLENGE}"
