#!/usr/bin/with-contenv bash

#======================================================================================================================
# Check for clean install
#======================================================================================================================

source /etc/functions/directories.sh

CONFIG=${SSL_CERTS}/getssl.cfg
if [ ! -f ${CONFIG} ] || [ "${SSL_CLEAN_INSTALL}" = "1" ] ; then

    if [ "${SSL_CLEAN_INSTALL}" = "1" ] ; then
        echo " - clean install detected, cleaning ${SSL_CERTS} and ${NGINX_SITES}..."
        rm -rf ${SSL_CERTS}/*
        rm -rf ${NGINX_SITES}/*
        echo " - done."
    fi

    echo " - creating global configuration..."
    gomplate \
        -o ${CONFIG}\
        -f /etc/templates/global.conf.tmpl
    echo " - done."

    echo " - generating dhparam..."
    openssl dhparam -out ${SSL_CERTS}/dhparam.pem 4096
    echo " - done."
    
fi


#======================================================================================================================
# Run initialisation script
#======================================================================================================================

init
