#!/usr/bin/with-contenv bash


if [ "${#DOMAINS[@]}" = "0" ] ; then
    echo " - no domains have been registered for SSL."
    exit 1
fi

#======================================================================================================================
# Setup each primary domain
#======================================================================================================================

echo " - creating SSL configuration..."
for D in "${!DOMAINS[@]}" ; do
    echo " - domain ${D}..."
    getssl -w /ssl/certs -d -c ${D}
done
echo " - done."
