#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Check for clean install
#======================================================================================================================

if [ "${PROXY_CLEAN_INSTALL}" = "1" ] ; then

    bcg-echo "Clean install detected..."
    bcg-rmrf "${PROXY_SSL_GLOBAL_CFG}"
    bcg-rmrf "${PROXY_SSL_DHPARAM}"
    bcg-rmrf "${PROXY_SSL_CERTS}/*"
    bcg-rmrf "${PROXY_SITES}/*"
    bcg-done

fi


#======================================================================================================================
# Run initialisation script
#======================================================================================================================

ssl-init
