#!/usr/bin/with-contenv bash

#======================================================================================================================
# Check for clean install
#======================================================================================================================

if [ ! -f ${SSL_GLOBAL_CFG} ] || [ "${CLEAN_INSTALL}" = "1" ] ; then

    if [ "${CLEAN_INSTALL}" = "1" ] ; then
        _echo "Clean install detected, cleaning ${SSL_CERTS} and ${SITES}..."

        if [ -z "${SSL_GLOBAL_CFG}" ] ; then
            _error "SSL_GLOBAL_CFG not defined."
            exit 1
        else
            rm -f ${SSL_GLOBAL_CFG}
        fi

        if [ -z "${SSL_CERTS}" ] ; then
            _error "SSL_CERTS not defined."
            exit 1
        else
            rm -rf ${SSL_CERTS}/*
        fi

        if [ -z "${SITES}" ] ; then
            _error "SITES not defined."
            exit 1
        else
            rm -rf ${SITES}/*
        fi

        _done
    fi
    
fi


#======================================================================================================================
# Run initialisation script
#======================================================================================================================

ssl-init
