#!/usr/bin/with-contenv bash

set -euo pipefail


#======================================================================================================================
# Check for clean install
#======================================================================================================================

_echo "Generating default server configuration..."
gomplate \
    -o ${SITES}/default.conf \
    -f ${TEMPLATES}/nginx-default.conf.tmpl
_done
