#!/usr/bin/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Install Nginx stream module, required for DNS over TLS.
#======================================================================================================================

if [ "${PROXY_ENABLE_DOT}" = "1" ] ; then

    # check required upstream
    [[ -z "${PROXY_UPSTREAM_DNS-}" ]] && bf-error "PROXY_UPSTREAM_DNS must be set to enable DNS over TLS."

    bf-echo "Enabling DNS over TLS..."

    # add Nginx stream module
    bf-echo " .. adding Nginx strem module"
    apk add --no-cache \
        nginx-mod-stream

    # generate DOT config
    bf-echo " .. generating configuration"
    bf-esh ${BF_TEMPLATES}/nginx-dot.conf.esh ${NGINX_MODULES}/dot.conf

    bf-done

fi
