#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Clear access and error logs to prevent files getting huge.
#======================================================================================================================

nginx-clear-logs
