#!/bin/bash


#======================================================================================================================
# Run checks.
#======================================================================================================================

source ${BF_INC}/proxy-check.sh


#======================================================================================================================
# Require source files.
#======================================================================================================================

source ${BF_INC}/proxy-init-domain.sh
source ${BF_INC}/proxy-replace.sh
source ${BF_INC}/proxy-setup-global.sh
source ${BF_INC}/proxy-setup-nginx.sh
source ${BF_INC}/proxy-setup-ssl.sh


#======================================================================================================================
# Set up global SSL configuration.
#======================================================================================================================

bf-echo "Setting up getssl..." "proxy/init-all"
setup-global
bf-done "proxy/init-all"


#======================================================================================================================
# Set up Nginx and SSL for proxy server.
#======================================================================================================================

bf-echo "Initialising Nginx and SSL for proxy server ${PROXY_URI}..." "proxy/init-all"
init-proxy
bf-done "proxy/init-all"


#======================================================================================================================
# Set up Nginx and SSL for each domain.
#======================================================================================================================

bf-echo "Initialising Nginx and SSL for all domains..." "proxy/init-all"
for DN in "${DOMAINS[@]}" ; do

    bf-echo " .. ${DN}" "proxy/init-all"
    init-domain "${DN}"
    bf-ok "  . done." "proxy/init-all"

done
bf-done "proxy/init-all"
