#!/bin/bash


#======================================================================================================================
# Run checks.
#======================================================================================================================

source ${BF_INC}/proxy-check.sh


#======================================================================================================================
# Require source files.
#======================================================================================================================

source ${BF_INC}/proxy-init-domain.sh
source ${BF_INC}/proxy-replace.sh
source ${BF_INC}/proxy-setup-global.sh
source ${BF_INC}/proxy-setup-nginx.sh
source ${BF_INC}/proxy-setup-ssl.sh


#======================================================================================================================
# Set up global SSL configuration.
#======================================================================================================================

bf-echo "Setting up getssl..." "proxy/init"
setup-global
bf-done "proxy/init"


#======================================================================================================================
# Initialise Nginx and SSL for requested domain.
#======================================================================================================================

if [ "${1}" = "proxy" ] || [ "${1}" = "${PROXY_DOMAIN}" ] ; then

    bf-echo "Initialising Nginx and SSL for proxy domain ${PROXY_DOMAIN}..." "proxy/init"
    init-proxy

else

    bf-echo "Initialising Nginx and SSL for ${1}..." "proxy/init"
    init-domain "${1}"

fi

bf-done "proxy/init"
