#!/command/with-contenv bash

export BF_E=`basename ${0}`


#======================================================================================================================
# Run checks.
#======================================================================================================================

source ${BF_INC}/proxy-check.sh


#======================================================================================================================
# Require source files.
#======================================================================================================================

source ${BF_INC}/proxy-replace.sh
source ${BF_INC}/proxy-setup-global.sh
source ${BF_INC}/proxy-setup-nginx.sh
source ${BF_INC}/proxy-setup-ssl.sh


#======================================================================================================================
# Set up global SSL configuration.
#======================================================================================================================

bf-echo "Setting up getssl..."
setup-global
bf-done


#======================================================================================================================
# Set up Nginx and SSL for proxy server.
#======================================================================================================================

bf-echo "Setting up default server ${PROXY_URI}..."

bf-echo "  . Nginx..."
setup-nginx 1 ${PROXY_URI} "http://localhost" ""

bf-echo "  . SSL..."
setup-ssl ${PROXY_URI} ""

bf-ok "  . done."


#======================================================================================================================
# Set up Nginx and SSL for each domain.
#======================================================================================================================

bf-echo "Setting up domains..."
for DN in "${!DOMAINS[@]}" ; do

    UP=${DOMAINS[${DN}]}  # upstream server
    AL=${ALIASES[${DN}]}  # aliases
    CF=${NGXCONF[${DN}]}  # use default / custom Nginx config

    bf-echo " .. ${DN}"

    bf-echo "  . Nginx..."
    setup-nginx 0 ${DN} "${UP}" "${AL}" "${CF}"

    bf-echo "  . SSL..."
    setup-ssl ${DN} "${AL}"

    bf-ok "  . done."

done
bf-ok "Domains set up."
