#!/bin/bash


#======================================================================================================================
# Run checks and include ssl functions.
#======================================================================================================================

source ${BF_INC}/proxy-check.sh
source ${BF_INC}/proxy-setup-ssl.sh


#======================================================================================================================
# Request certificates for all domains.
#
# getssl flags
#   -U  stop upgrade checks
#   -w  set working directory
#======================================================================================================================

request() {
    ${PROXY_GETSSL} -U -w ${PROXY_SSL_CERTS} "${1}"
    create-pem "${1}"
}


#======================================================================================================================
# Get certificate for the proxy server base domain.
#======================================================================================================================

bf-echo "Requesting proxy server certificate..." "proxy/request"
bf-debug " .. ${PROXY_URI}"
request "${PROXY_URI}"
bf-done "proxy/request"


#======================================================================================================================
# Get certificates for all registered domains.
#======================================================================================================================

bf-echo "Requesting domain certificates..." "proxy/request"
for DN in "${!DOMAINS[@]}" ; do
    bf-debug " .. ${DN}" "proxy/request"
    request "${DN}"
done
bf-done "proxy/request"
