#!/bin/bash


#======================================================================================================================
# Run checks and include ssl functions.
#======================================================================================================================

source ${BF_INC}/proxy-check.sh
source ${BF_INC}/proxy-setup-ssl.sh


#======================================================================================================================
# Get certificate for the proxy server base domain.
#======================================================================================================================

bf-echo "Requesting proxy server certificate..." "proxy/request-all"
bf-debug " .. ${PROXY_DOMAIN}"
request "${PROXY_DOMAIN}"
bf-done "proxy/request-all"


#======================================================================================================================
# Get certificates for all registered domains.
#======================================================================================================================

bf-echo "Requesting domain certificates..." "proxy/request-all"
for DN in "${DOMAINS[@]}" ; do
    bf-debug " .. ${DN}" "proxy/request-all"
    request "${DN}"
done
bf-done "proxy/request-all"
