#!/bin/bash


#======================================================================================================================
# Run checks and include ssl functions.
#======================================================================================================================

source ${BF_INC}/proxy-check.sh
source ${BF_INC}/proxy-setup-ssl.sh


#======================================================================================================================
# Run update.
#
# getssl flags
#   -d  enable debug output
#   -U  stop upgrade checks
#   -w  set working directory
#   -a  check all certificates
#======================================================================================================================

bf-echo "Updating all SSL certificates..." "proxy/update"
${PROXY_GETSSL} ${PROXY_GETSSL_FLAGS} -w ${PROXY_SSL_CERTS} -a
bf-done "proxy/update"


#======================================================================================================================
# Update all pem files (easier than working out which have been changed).
#======================================================================================================================

bf-echo "Updating pem files..." "proxy/update"
create-pem ${PROXY_URI}
for DN in "${!DOMAINS[@]}" ; do create-pem "${DN}" ; done
bf-done "proxy/update"
