#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Run SSL update executable and log output to /ssl directory.
#======================================================================================================================

if [ "${PROXY_ENABLE_AUTO_UPDATE}" = "1" ] ; then
    ssl-update > ${PROXY_SSL}/update.log
fi
