#!/usr/bin/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Run SSL update executable and log output to /ssl directory.
#======================================================================================================================

ssl-update > ${PROXY_SSL}/update.log
