#!/usr/bin/with-contenv bash

export BCG_E=`basename ${0}`


#======================================================================================================================
# Run checks and include ssl functions.
#======================================================================================================================

source ${BCG_INC}/proxy-check.sh
source ${BCG_INC}/proxy-setup-ssl.sh


#======================================================================================================================
# Request certificates for all domains.
#
# getssl flags
#   -U  stop upgrade checks
#   -w  set working directory
#======================================================================================================================

request() {
    ${PROXY_GETSSL} -U -w ${PROXY_SSL_CERTS} "${1}"
    create-pem "${1}"
}


#======================================================================================================================
# Get certificate for the proxy server base domain.
#======================================================================================================================

bcg-echo "Requesting proxy server certificate..."
request "${PROXY_URI}"
bcg-done


#======================================================================================================================
# Get certificates for all registered domains.
#======================================================================================================================

bcg-echo "Requesting domain certificates..."
for DN in "${!DOMAINS[@]}" ; do
    bcg-debug " .. ${DN}"
    request "${DN}"
done
bcg-done
